services:
  justinject:
    image: justinject
    container_name: broker
    command: ["broker"]
    ports:
      - 8080:8080
    environment:
      - OTEL_ENDPOINT_GRPC=grafana:4317
      - OTEL_ENDPOINT_HTTP=grafana:4318
  otel:
    image: grafana/otel-lgtm
    container_name: grafana
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
