apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-apis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-apis
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-apis
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-apis
subjects:
  - kind: ServiceAccount
    name: node-apis
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      serviceAccountName: node-apis
      containers:
        - name: broker
          image: justinject:latest
          imagePullPolicy: IfNotPresent
          command:
            - tail -f /dev/null
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: job
              mountPath: /k8s/job.tmpl
              subPath: job.tmpl
      volumes:
        - name: job
          configMap:
            name: broker-configmap
